config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts do
      resources :comments
    end
  end

  namespace :api, defaults: { format: :json } do
    post 'login', to: 'authentication#authenticate'
    post 'signup', to: 'users#create'
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end

  get 'new', to: 'posts#new' # new post

  # Very pretty -->
  # namespace :api, path: '', constraints: { subdomain: 'api' } do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Roles = %i[admin default]

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true

  ## Custom

  def recent_posts(quantity)
    posts.order(created_at: :desc).limit(quantity)
  end

  def three_recent_posts
    recent_posts(3)
  end

  def photo_link
    photo == '' ? 'no_picture.jpg' : photo
  end

  def is?(requested_role)
    role == requested_role.to_s
  end

  ## Extending as_json method

  def as_json(_options = {})
    super(only: %i[id name bio posts_counter])
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_action :authorize_request, only: :create

  def index
    @users = User.all

    render json: @users
  end

  def show
    @user = User.find(params[:id])

    render json: @user
  end

  def create
    user = User.create!(user_params)
    auth_token = AuthenticateUser.new(user.email, user.password).call
    response = { message: Message.account_created, auth_token: auth_token }
    json_response(response, :created)
  end

  private

  def user_params
    params.permit(
      :name,
      :email,
      :bio,
      :photo,
      :password
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.three_recent_posts
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_post_card.html.erb
<article>
  <div class="border-t border-opacity-50 mb-6"></div>
  <a href="<%= user_post_path(@user, post) %>">
    <div class="flex flex-col">
      <h4 class="font-bold text-lg text-red-400 opacity-80 mb-4">
        <%= post.title %>
      </h4>
      <p class="text-gray-400 mb-2">
        <%= post.text %>
      </p>
      <div class="self-end flex gap-x-6 text-gray-400 text-opacity-75">
        <p>Likes:
          <span class="text-red-400">
            <%= post.likes_counter %>
          </span>
        </p>
        <p>Comments: 
          <span class="text-red-400">
            <%= post.comments_counter %>
          </span>
        </p>
      </div>
    </div>
  </a>
</article>

app/views/users/_user_card.html.erb
<article>
  <%= link_to (user_path(user)) do %>
    <div class="flex flex-col sm:flex-row bg-gradient-to-br from-indigo-800 to-indigo-900 rounded-lg shadow-lg">
      <div class="flex-none w-full h-48 sm:w-48 relative">
        <%= image_tag user.photo_link,
            alt: 'user',
            class: 'absolute inset-0 w-full h-full object-cover rounded-l-lg' %>
      </div>
      <div class="w-full flex flex-wrap justify-between items-end px-12 py-6 h-48">
        <h2 class="font-bold text-3xl self-center">
          <%= user.name %>
        </h2>
        <p>Number of posts:
          <span class="font-bold text-red-400">
            <%= user.posts_counter %>
          </span></p>
      </div>
    </div>
  <% end %>
</article>

app/views/users/index.html.erb
<div class="flex flex-col gap-12 sm:px-0">
  <% if can? :read , @user %>
    <% @users.includes(:posts).each do |user| %>
      <%= render 'user_card', user: user %>
    <% end %>
    <% if @users.length == 0 %>
      <div class="text-center flex flex-col h-72 justify-center bg-indigo-900 rounded-xl shadow-xl mt-20 px-4">
        <h2 class="text-3xl mb-2 font-bold">You're the first user in our App, congratulations.</h2>
        <p class="text-xl opacity-70">Please log in to start creating awesome posts!</p>
      </div>
    <% end %>
  <% else %>
    <div class="flex flex-col justify-center p-4 mt-12 sm:flex-row bg-gradient-to-br from-indigo-800 to-indigo-900 rounded-lg shadow-lg">
      <h2 class="text-3xl mb-2 font-bold">Who are you???!!</h2>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="flex flex-col sm:px-12 bg-gradient-to-br from-indigo-800 to-indigo-900 rounded-lg shadow-lg">
  <div class="flex flex-col sm:flex-row py-6">
    <div class="flex-none w-full h-48 sm:w-48 relative">
      <%= image_tag @user.photo_link,
            alt: 'user',
            class: 'absolute inset-0 w-full h-full object-cover rounded-lg' %>
    </div>
    <div class="w-full flex flex-col items-end py-12 h-48">
      <h2 class="font-bold text-3xl">
        <%= @user.name %>
      </h2>
      <span class="font-light mb-8">@userName</span>
      <p class="text-gray-400">Number of posts: <span class="font-bold text-red-400">
          <%= @user.posts_counter %>
        </span>
      </p>
    </div>
  </div>
  <div class="py-6">
    <h3 class="font-bold text-xl text-red-400 mb-4">About...</h3>
    <p class="text-lg text-gray-200">
      <%= @user.bio %>
    </p>
  </div>
  <div class="flex flex-col py-6 gap-y-12 mb-4">
    <% @posts.each do |post| %>
      <%= render 'post_card', post: post %>
    <% end %>
  </div>
  <a href="/users/<%= @user.id %>/posts" class="bg-indigo-700 mx-auto w-max px-16 py-3 mb-6">See all posts</a>
</div>