config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: %i[index show] do
    resources :posts do
      resources :comments
    end
  end

  namespace :api, defaults: { format: :json } do
    post 'login', to: 'authentication#authenticate'
    post 'signup', to: 'users#create'
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end

  get 'new', to: 'posts#new' # new post

  # Very pretty -->
  # namespace :api, path: '', constraints: { subdomain: 'api' } do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_new_comment.html.erb
<% if user_signed_in? %>
  <div class="flex mb-6">
    <div class="flex-none w-14 h-14 relative mr-6">
      <%= image_tag current_user.photo_link,
              alt: 'user',
              class: 'absolute inset-0 w-full h-full object-cover rounded-full' %>
    </div>

    <%= form_with model: [@user, @post, @post.comments.build],
  :html => { :class => "flex items-center flex-wrap"} do |f| %>
      <%= f.text_field :text,
    placeholder: "Write something...", 
    class: "bg-gray-900 px-6 py-2 rounded-lg border-0 text-gray-400 text-sm mb-2" %>
      <%= f.submit "Comment",
    class: "bg-gray-700 px-6 py-2 sr-only focus:not-sr-only" %>
    <% end %>
  </div>
<% else %>
  <div class="border-t border-opacity-50 mb-6 w-full"></div>
  <p class="text-center text-gray-400 text-opacity-75">Please <%= link_to 'sign in', new_user_session_path, class: "underline" %> to comment.</p>
<% end %>

app/views/shared/_post_comment.erb
<div class="flex mb-6">
  <div class="flex-none w-14 h-14 relative mr-6">
    <%= image_tag 'portrait-medium.jpg',
            alt: 'user',
            class: 'absolute inset-0 w-full h-full object-cover rounded-full' %>
  </div>
  <div class="bg-gray-900 px-6 py-2 rounded-lg">
    <h5 class="font-bold text-gray-400 text-sm mb-1">
      <%= comment.author.name %>
    </h5>
    <p class="text-gray-400 text-sm">
      <%= comment.text %>
    </p>
  </div>
</div>

app/views/shared/_post_comment.html.erb
<div class="flex mb-6">
  <div class="flex-none w-14 h-14 relative mr-6">
    <%= image_tag comment.author.photo_link,
            alt: 'user',
            class: 'absolute inset-0 w-full h-full object-cover rounded-full' %>
  </div>
  <div class="bg-gray-900 px-6 py-2 rounded-lg">
    <h5 class="font-bold text-gray-400 text-sm mb-1">
      <%= comment.author.name %>
    </h5>
    <p class="text-gray-400 text-sm flex justify-between">
      <%= comment.text %>

      <% if can? :delete, comment %>
        <%= link_to (user_post_comment_path(comment.post.author, comment.post, comment)), method: :delete do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="ml-4 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
        <% end %>
      <% end %>

    </p>
  </div>
</div>